installCRDs: true
# nodeSelector: 
#   node-role.kubernetes.io/control-plane: ""
# tolerations:
# - key: "node-role.kubernetes.io/control-plane"
#   effect: "NoSchedule"

# webhook:
#   nodeSelector: 
#     node-role.kubernetes.io/control-plane: ""
#   tolerations:
#   - key: "node-role.kubernetes.io/control-plane"
#     effect: "NoSchedule"

# cainjector:
#   nodeSelector: 
#     node-role.kubernetes.io/control-plane: ""
#   tolerations:
#   - key: "node-role.kubernetes.io/control-plane"
#     effect: "NoSchedule"